import type { Message } from '@/models/message.model'

/**
 * Options for customising LLM completion requests.
 */
interface CompletionOptions {
  /**
   * When `true`, instructs the model to return a valid JSON object.
   * Availability depends on the underlying provider.
   */
  jsonMode?: boolean
  /**
   * Sampling temperature (0–2). Higher values produce more varied output;
   * lower values make output more focused and deterministic.
   */
  temperature?: number
  /**
   * Nucleus sampling probability threshold (0–1). Limits token selection to the
   * cumulative top-p probability mass.
   */
  topP?: number
}

/**
 * Token usage returned by a chat provider when the underlying API exposes it.
 */
interface CompletionUsage {
  /** Tokens generated by the model. */
  completionTokens?: number
  /** Tokens sent to the model. */
  promptTokens?: number
  /** Total prompt and completion tokens. */
  totalTokens?: number
}

/**
 * Structured completion result for providers that can expose production metadata.
 */
interface CompletionResult {
  /** Text returned by the model. */
  content: string
  /** Model identifier used for the request. */
  model?: string
  /** Provider identifier such as `openai`, `anthropic`, or `gemini`. */
  provider?: string
  /** Token usage if returned by the provider. */
  usage?: CompletionUsage
}

/**
 * Minimal contract for LLM chat-completion providers.
 *
 * Implement this interface to integrate any chat model into the RAG pipeline.
 *
 * @example
 * class MyProvider implements ChatProvider {
 *   async complete(messages: Message[], options?: CompletionOptions): Promise<string> {
 *     // call your LLM API here
 *   }
 * }
 */
interface ChatProvider {
  /**
   * Sends a sequence of messages to the underlying LLM and returns the model's reply.
   *
   * @param {Message[]} messages - Conversation messages in chronological order.
   *   `'system'` messages define instructions; `'user'`/`'assistant'` messages form the dialogue.
   * @param {CompletionOptions} [options] - Optional settings such as temperature or JSON output mode.
   * @returns {Promise<string>} A promise that resolves to the model's text response.
   */
  complete(messages: Message[], options?: CompletionOptions): Promise<string>
  /**
   * Optional structured completion API for providers that can expose model and
   * token usage metadata. Custom providers can implement this without changing
   * the plain `complete()` behaviour expected by existing callers.
   */
  completeWithMetadata?(messages: Message[], options?: CompletionOptions): Promise<CompletionResult>
}

export type {
  ChatProvider,
  CompletionOptions,
  CompletionResult,
  CompletionUsage,
}
